version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "127.0.0.1:8027:8081"
    depends_on:
      - mongo

  smtpd:
    container_name: smtpd
    image: rnwood/smtp4dev:linux-amd64-v3
    ports:
      - "127.0.0.1:8025:80"
      - "127.0.0.1:25:25"
