version: "3.7"
services:
  harbor-mongo:
    container_name: harbor-mongo
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"

  harbor-mongo-web:
    container_name: harbor-mongo-web
    image: mongo-express
    ports:
      - "127.0.0.1:8027:8081"
    environment:
      - "ME_CONFIG_MONGODB_SERVER=harbor-mongo"
    depends_on:
      - harbor-mongo

  harbor-rabbitmq:
    container_name: harbor-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "127.0.0.1:5672:5672"

  harbor-scheduler:
    container_name: harbor-scheduler
    build:
      context: .
      dockerfile: celery-scheduler.dockerfile
    environment:
      - "CELERY_RABBITMQ_HOST=harbor-rabbitmq"
    depends_on:
      - harbor-rabbitmq

  harbor-worker:
    container_name: harbor-worker
    build:
      context: .
      dockerfile: celery-worker.dockerfile
    environment:
      - "CELERY_RABBITMQ_HOST=harbor-rabbitmq"
      - "MONGO_HOST=harbor-mongo"
    depends_on:
      - harbor-rabbitmq

  harbor-flower:
    container_name: harbor-flower
    image: mher/flower
    environment:
      - "FLOWER_BASIC_AUTH=admin:admin"
    command:
      - "--broker=amqp://guest@harbor-rabbitmq:5672//"
      - "--broker_api=http://guest:guest@harbor-rabbitmq:15672/api/"
    ports:
      - "127.0.0.1:8055:5555"
    depends_on:
      - harbor-rabbitmq

  harbor-smtpd:
    container_name: harbor-smtpd
    image: rnwood/smtp4dev:v3
    ports:
      - "127.0.0.1:8025:80"
      - "127.0.0.1:25:25"
