name: Build latest Docker image

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest --cov=harbor --cov-report=xml

      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests

      - name: Upload coverage to CodeClimate
        uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: pytest --cov=harbor --cov-report=lcov
          coverageLocations: "./coverage.lcov:lcov"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: "kinkyharbor/kinkyharbor-backend-fastapi"
          TAG_NAME: "latest"
          LATEST: "true"
